Run tmate debugging session only if workflow_dispatch debug_enabled is true
ddev/ddev-addon-template pull request #20
Opened 2023-02-08 09:18 UTC by julienloizelet

Hi,
if we use the `workflow_dispatch` to launch the "tests" action, the `tmate debugging session` step runs even if we let the default `debug_enabled` input to `false`.

This PR fixes it and runs the `tmate debugging session` step only if the value of `debug_enabled` has been explicitly set to `true`.

2023-02-08 15:20 UTC, rfay requested changes
Thanks for this! I think the best thing is to make it a boolean, it also then shows up as a checkbox.

2023-02-08 15:20 UTC, rfay commented on .github/workflows/tests.yml
> +      if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled == 'true'}}
I think the real problem is that we need this:
```
      debug_enabled:
        description: 'Enable debug mode'
        type: boolean
        required: false
        default: false
```

It's the `type: boolean`; which makes it into a checkbox, also easier to use.

2023-02-09 04:31 UTC, julienloizelet commented on .github/workflows/tests.yml
> +      if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled == 'true'}}
Hi, I just pushed a new commit with the boolean input.

I also removed the `github.event_name == 'workflow_dispatch' condition test, as I guess inputs are only used in the workflow_dispatch flow.

2023-02-09 17:14 UTC, rfay reviewed
Just happened to notice this obsolete piece. Are you now about to run tmate properly (with checkbox) on your fork?

2023-02-09 17:14 UTC, rfay commented on .github/workflows/tests.yml
>          docker pull memcached:1.6 >/dev/null
```suggestion
```

2023-02-10 00:34 UTC, julienloizelet commented on .github/workflows/tests.yml
>          docker pull memcached:1.6 >/dev/null
I removed the obsolete piece. 

Yes, I tested workflow_dispatch with the checkbox on my fork and it worked as expected:
- [unchecked (no tmate test)](https://github.com/julienloizelet/ddev-addon-template/actions/runs/4139579738/jobs/7157308439)
- [ checked (tmate test)](https://github.com/julienloizelet/ddev-addon-template/actions/runs/4139579178/jobs/7157307196)

2023-02-10 00:51 UTC, rfay approved these changes
Looks right to me, thanks so much for fixing this up. I had discovered this in some other add-on but apparently hadn't properly put it here. I think it may have changed upstream over time as well.

2023-02-10 15:59 UTC, merged