Move health checks to a separate function in bats test file
ddev/ddev-addon-template pull request #24
Opened 2023-03-31 08:37 UTC by MurzNN

Now, regarding to the template file, we have to write checks twice: 
- In `@test "install from directory"`
- And in `@test "install from release"` - the same lines.

Will be good to move that to a separate function, to not have two places to manage them. 

So, I've created a function `health_checks()` that contains only a single instance of checks.

And have moved it to the top, because it will be edited more frequiently, than test functions.

2023-03-31 16:12 UTC, rfay requested changes
Please run tests manually and get them to pass...

2023-04-01 03:40 UTC, MurzNN commented
Hmm, the tests are running well locally:
![image](https://user-images.githubusercontent.com/336662/229263971-fb927a0c-4a84-4f79-94e5-cfdfc7cb65fd.png)
Will check what are the difference with the pipeline.

2023-04-01 03:51 UTC, MurzNN commented
Seems `bats` doesn't support functions with all commented lines, so I've just added one real line there and it starts working:
![image](https://user-images.githubusercontent.com/336662/229264199-2c30badc-78f9-4047-89fe-f2895f7c8da0.png)

2023-04-01 15:24 UTC, rfay approved these changes
Thanks! It's certainly an improvement.

2023-04-01 15:24 UTC, merged