Add a section how to debug Github Actions with tmate to the README.md
ddev/ddev-addon-template pull request #29
Opened 2023-07-08 21:07 UTC by rpkoller

## The Issue
An initial draft for adding instructions how to debug Github Actions with tmate to the project's README.md file. I am uncertain if the steps i've listed are too granular. But it covers stepping stones i've personally ran into  as well as guidance for github'S workflow interface you have to click through to get to the current task list for a job - that is sort of suboptimal and unintuitive. therefore i went with the a bit more verbose write up. But all input and feedback is welcome. thanks. 

p.s. after finishing and agreeing on the documentation for the addon-template i will go on add an addition to ddev.readthedocs.com as well as discussed on discord.

## How This PR Solves The Issue

## Manual Testing Instructions

## Automated Testing Overview

## Related Issue Link(s)

## Release/Deployment Notes

2023-07-12 21:02 UTC, rfay requested changes
Thanks! Minor suggestions.

2023-07-12 21:02 UTC, rfay commented on README.md
> +1. You need a SSH-key registered with Github. You either pick the key you already authenticate with `github.com` or you create a dedicated new one with `ssh-keygen -t ed25519 -a 64 -f tmate_ed25519 -
I think it's best to streamline this with "Use a key that is configured with github" and give a link to Github's docs.

2023-07-12 21:02 UTC, rfay commented on README.md
> +2. Add the following snippet to `~/.ssh/config`
This step is unnecessary normally, but perhaps you have gobs of keys.

2023-07-12 21:02 UTC, rfay commented on README.md
> +4. By clicking the `Run workflow`- button you have the option to the select the branch to run the workflow from and activate `tmate` by checking the `Debug with tmate` checkbox for this run.
```suggestion
4. Click the `Run workflow`- button and you will have the option to the select the branch to run the workflow from and activate `tmate` by checking the `Debug with tmate` checkbox for this run.
```

2023-07-12 21:02 UTC, rfay commented on README.md
> +8. Wait until the current task list reaches the `tmate debugging session` section and the output shows something like that:
```suggestion
8. Wait until the current task list reaches the `tmate debugging session` section and the output shows something like:
```

2023-07-12 21:02 UTC, rfay commented on README.md
> +For a more detailed documentation about `tmate` see [Debug your GitHubActions by using tmate](https://mxschmitt.github.io/action-tmate/)
Another whole section could be about how to actually debug bats, which I think you're working on here.

2023-08-31 16:08 UTC, rpkoller commented on README.md
> +2. Add the following snippet to `~/.ssh/config`
in that case i consider it useful because with the wildcard you make sure that the different subdomains are all covered with the same ssh key. and i struggled at the beginning because i'Ve used the specific domain and subdomain and then ran into another one.

2023-08-31 16:08 UTC, rpkoller commented on README.md
> +For a more detailed documentation about `tmate` see [Debug your GitHubActions by using tmate](https://mxschmitt.github.io/action-tmate/)
i agree a dedicated section about bats might be helpful. but i have to admit i haven't thought nor was working on it. i am in lack of bats expertise also. the tests i'Ve used for spidergram were more than basic and rudimental.

2023-08-31 16:08 UTC, rpkoller commented on README.md
> +1. You need a SSH-key registered with Github. You either pick the key you already authenticate with `github.com` or you create a dedicated new one with `ssh-keygen -t ed25519 -a 64 -f tmate_ed25519 -
hm registered is suboptimal i agree but configured with github is also unprecise. github is using the terminology of "associated with your account". maybe something like: 

You need a SSH-key associated with your [GitHub account](https://github.com/settings/keys). You either pick the key you already use on `github.com` or you create a dedicated new one with `ssh-keygen -t ed25519 -a 64 -f tmate_ed25519 -C "$(date +'%d-%m-%Y')"` and add it to `https://github.com/settings/keys`.

2023-09-05 16:01 UTC, rfay commented on README.md
> +1. You need a SSH-key registered with Github. You either pick the key you already authenticate with `github.com` or you create a dedicated new one with `ssh-keygen -t ed25519 -a 64 -f tmate_ed25519 -
That explanation works for me, thanks.

2023-09-05 16:02 UTC, rfay commented on README.md
> +2. Add the following snippet to `~/.ssh/config`
I typically only have a single ssh key ever configured on github.

2023-09-05 16:03 UTC, rfay approved these changes
I think it's important to get this in. I'll pull now, cleanups are welcome.

2023-09-05 16:03 UTC, merged